name: smartsellpro
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.2
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.8
  firebase_core: ^1.22.0
  flutter_staggered_grid_view: ^0.6.2
  firebase_storage: ^10.3.8
  font_awesome_flutter: ^10.2.1
 
  firebase_auth: ^3.9.0
  get: ^4.6.5 
  toast: ^0.3.0
  fluttertoast: ^8.0.9
  flutter_custom_dialog: ^1.3.0
  image_picker: ^0.8.5+3
  path: ^1.8.2
  carbon_icons: ^0.0.1+2
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - asset/image/